### ISSUE TITLE
Segfault with sleepwalk.mod

### ISSUE THREAD

**Issue by cyberic99** [superctr/mod2vgm#1]
Hello and thank you for for this software!

When converting this .mod:

http://modland.com/pub/modules/Soundtracker/Karsten%20Obarski/sleepwalk.mod

I get a segmentation fault.

I started to look for the cause of the crash.

First, it was crashing on pattern 0x6F (the song contains 0xd7 patterns)

By raising the max pattern number to 256 in mod2vgm.h, the conversion now crashed at pattern 0xbe.

No more info ATM, sorry

Thanks!

**Comment by superctr** [comment]
The problem is that the module only contains 15 sample slots (pre-Protracker format) which is unsupported. You must convert it to a Protracker format MOD with 31 sample slots, it's as easy as loading it and saving it in OpenMPT.

**Comment by cyberic99** [comment]
that indeed fixed the problem, thank you!
