### ISSUE TITLE
mod2vgm won't work

### ISSUE THREAD

**Issue by zeroflafi** [superctr/mod2vgm#2]
When I launch it it closes immitedly. When I spam click it an empty comand promt shows up. I tried using every compability mode there is. I know it was last updated in 2016 but I hope someone can help me.

**Comment by superctr** [comment]
There's no GUI, it's a command line application. It's possible to drag and drop files but then you cannot adjust all settings.

**Comment by zeroflafi** [comment]
I couldn't drag files into it and the command prompt stopped showing up even after spam clicking.

**Comment by superctr** [comment]
As I have said it's a command line application. On windows you can hold shift and rightclick in the same folder to open a powershell window. Then you can type "mod2vgm" to get a list of options. I'm not going to teach you how to use a command line, so you're on your own from now on.
